name: ${name}
version: ${version}
api-version: 1.19
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
author: ${author}
commands:
    randomize:
        description: Resets the mapping
        usage: /randomize
        permission: randomcraft.command
permissions:
    randomcraft.command:
        description: Allows you to use the command /randomcraft
        default: op